**Dataset:** HRDataset_v14.csv

**Context:** HR Analytics

In this notebook, I explore an HR dataset to analyze employee structure and organizational trends.
The focus is on **data reorganization, filtering, and multi-index structures** using Python and Pandas.
I applied techniques for **data cleaning**, transforming and managing **DataFrames and Series**, and building insights about workforce composition and turnover.

**Skills demonstrated:** Data cleaning, multi-index DataFrames, filtering, organizational analysis, data persistence

**Questão 1 - Carregamento e exploração inicial**

1. A biblioteca pandas foi importada; a função "read_csv" foi chamada para ler o dataset em questão; a função do pandas "set_option" foi utilizada aqui com os argumentos "display.max_columns" e "None" com o objetivo de mostrar toda as colunas existentes no dataset original.

2. Neste contexto o método "info()" foi utilizado para trazer os nomes, os tipos e a quantidade de colunas do dataset. 
Após análise podemos identificar as colunas "ManagerName", "PerformanceScore" e "Gender ID" que deveriam ser convertidas para o tipo "category".

3. Como resultado da operação realizada, um objeto do tipo Pandas Series foi selecionado, agora representando uma coluna "PerformanceScore" com seu índice associado.

In [1]:
# Questão 1.1
import pandas as pd
df= pd.read_csv("HRDataset_v14.csv")
pd.set_option("display.max_columns", None)


# Questão 1.2
df.info()


# Questão 1.3
performance_series= df["PerformanceScore"]
performance_series.head(10)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Position,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,0,19,Production Technician I,MA,1960,07/10/83,M,Single,US Citizen,No,White,7/5/2011,NaN,N/A-StillEmployed,Active,Production,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,1,27,Sr. DBA,MA,2148,05/05/75,M,Married,US Citizen,No,White,3/30/2015,6/16/2016,career change,Voluntarily Terminated,IT/IS,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,1,20,Production Technician II,MA,1810,09/19/88,F,Married,US Citizen,No,White,7/5/2011,9/24/2012,hours,Voluntarily Terminated,Production,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,0,19,Production Technician I,MA,1886,09/27/88,F,Married,US Citizen,No,White,1/7/2008,NaN,N/A-StillEmployed,Active,Production,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,1,19,Production Technician I,MA,2169,09/08/89,F,Divorced,US Citizen,No,White,7/11/2011,9/6/2016,return to school,Voluntarily Terminated,Production,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

**Questão 2 - Seleção de dados para análise de desempenho**

1. Neste código aplicamos os filtros solicitados na questão, aplicamos a função ".loc[]" para que trouxesse apenas os registros que equivalessem aos filtros e visualizamos o resultado através do método ".head()".

2. Neste bloco de código foram filtrados apenas os empregados que possuem um número de ausência maior do 10 e que possuem um salário maior do que 80000.

3. Para realizar a filtragem em Python puro (sem a bliblioteca Pandas), começaríamos por abrir o arquivo CSV utilizando o módulo csv da bliblioteca padrão; percorreríamos linha a linha utilizando um "for"; aplicaríamos as condições da questão, mais de 10 ausências e salário superior a 80.000; armazenaríamos o resultado em uma lista.

In [2]:
# Questão 2.1
filtros= (df["EmploymentStatus"] == "Active") & (df["PerfScoreID"] == 3)
resultado= df.loc[filtros, ["Employee_Name", "Department", "PerformanceScore", "ManagerName"]]

# Questão 2.2
criterios= (df["Absences"] > 10) & (df["Salary"] > 80000)
saida= df.loc[criterios]

# Questão 2.1
resultado.head(10)

# Questão 2.3 - Markdown

,Employee_Name,Department,PerformanceScore,ManagerName
3,"Alagbe,Trina",Production,Fully Meets,Elijiah Gray
6,"Andreola, Colby",Software Engineering,Fully Meets,Alex Sweetwater
7,"Athwal, Sam",Production,Fully Meets,Ketsia Liebig
8,"Bachiochi, Linda",Production,Fully Meets,Brannon Miller
9,"Bacong, Alejandro",IT/IS,Fully Meets,Peter Monroe
13,"Barone, Francesco A",Production,Fully Meets,Kelley Spirea
17,"Beatrice, Courtney",Production,Fully Meets,Elijiah Gray
19,"Becker, Scott",Production,Fully Meets,Webster Butler
20,"Bernstein, Sean",Production,Fully Meets,Amy Dunn
21,"Biden, Lowan M",Production,Fully Meets,Ketsia Liebig

**Questão 3 - Estrutura com múltiplos índices e segmentação por gestor**

1. As colunas mencionadas foram selecionadas e armazenadas em um novo dataframe chamado "novo_df".

2. A função "set_index" do Pandas foi chamada para configurar as colunas "Department" e "ManagerName" como os indíces do novo dataframe.

3. O uso de multi-índices neste contexto ajuda a organizar os dados de acordo com os níveis hierárquicos, como "Department" - "Manager" - "Employee"; facilita a visualização do dataset e acaba por facilitar a interpretação e o entendimento dos dados; facilita a agregação dos dados e para além disso, há uma otimização dos dados, não tendo a necessidade de criar colunas adicionais ou múltiplos filtros.

In [3]:
# Questão 3.1
novo_df= df[["Department", "ManagerName", "PerformanceScore", "Salary"]]

# Questão 3.2
multi_index_df= novo_df.set_index(["Department", "ManagerName"])
multi_index_df.head(5)


# Questão 3.3 - Markdown

                                 PerformanceScore  Salary
Department        ManagerName
Production        Michael Albert          Exceeds   62506
IT/IS             Simon Roup          Fully Meets  104437
Production        Kissy Sullivan      Fully Meets   64955
                  Elijiah Gray        Fully Meets   64991
                  Webster Butler      Fully Meets   50825

**Questão 4 - Transformações e ajustes**

1. Nesta questão armazenamos na variável map_scores um dicionário correspondendo o valor ao seu correspondente númerico e em seguida aplicamos a função ".map" na coluna "PerformanceScore" utilizando como parâmetro a variável definida acima.

2. No código abaixo a expressão "Salary * (1 + Absences / 100) " é utilizada tendo como paramêtro as colunas "Salary" e "Absences", retornando um valor que indica o custo total do funcionário (salário + ausências) para a empresa.

3. Métricas ajustadas e calculadas como traz a coluna "Cost_Index" ajudam os gestores a tomar melhores decisões; tornam os dados mais fidedignos no que tange a realidade da empresa e dos seus funcionários; permite observar o gasto real da empresa e adiciona um peso relacionado ao comportamento (ausências).

In [21]:
# Questão 4.1
map_scores= {
    "Exceeds": 3,
    "Fully Meets": 2,
    "Needs Improvement": 1,
    "PIP": 0
}
df["PerformanceScore"]= df["PerformanceScore"].map(map_scores)
df[["Employee_Name", "PerformanceScore"]].head(10)

# Questão 4.2
df["Cost_Index"]= df["Salary"] * (1 + df["Absences"] / 100)
df[["Employee_Name", "Salary", "Absences", "Cost_Index"]].head(10)

# Questão 4.3 - Markdown

              Employee_Name  Salary  Absences  Cost_Index
0       Adinolfi, Wilson  K   62506         1    63131.06
1  Ait Sidi, Karthikeyan     104437        17   122191.29
2         Akinkuolie, Sarah   64955         3    66903.65
3              Alagbe,Trina   64991        15    74739.65
4          Anderson, Carol    50825         2    51841.50
5         Anderson, Linda     57568        15    66203.20
6           Andreola, Colby   95660        19   113835.40
7               Athwal, Sam   59365        19    70644.35
8          Bachiochi, Linda   47837         4    49750.48
9        Bacong, Alejandro    50178        16    58206.48

**Questão 5 - Persistência dos dados**

1. O dataframe criado na questão 3 e modificado na questão 4, com a coluna "Cost_Index" foi trazido para este código e tranformado em um CSV padrão (com vírgula) e outro com ponto e vírgula (;).

2. O método "read_csv" do pandas foi utilizado aqui para ler os dois CSVs e o método "display" para mostrar as 5 primeiras linhas de cada df retornado.

3. Caso o separador utilizado no salvamento não for o mesmo informado na leitura, o Pandas (ou outro software) pode ler todas as colunas como uma só string ou até mesmo gerar colunas extras incorretas; erros acontecem também quando a codificação na qual o arquivo foi salvo não é o mesmo no qual ele esta sendo lido, como exemplo: arquivo salvo em "UTF-8", mas lido em "Latin-1" pode acarretar em erros como "André" (com o acento agudo) aparecer como outro caractere.

In [27]:
# Questão 5.1
final_df= df[["Department", "ManagerName", "PerformanceScore", "Salary", "Cost_Index"]]
final_df.to_csv("Dataset_virgula.csv", index=False)
final_df.to_csv("Dataset_pontoevirgula.csv", sep=";", index=False)
final_df.head()

# Questão 5.2
df_virgula= pd.read_csv("Dataset_virgula.csv")
df_pontoevirgula= pd.read_csv("Dataset_pontoevirgula.csv", sep=";")

display(df_virgula.head())
display(df_pontoevirgula.head())

# Questão 5.3 - Markdown

          Department     ManagerName  PerformanceScore  Salary  Cost_Index
0  Production         Michael Albert               NaN   62506    63131.06
1              IT/IS      Simon Roup               NaN  104437   122191.29
2  Production         Kissy Sullivan               NaN   64955    66903.65
3  Production           Elijiah Gray               NaN   64991    74739.65
4  Production         Webster Butler               NaN   50825    51841.50

          Department     ManagerName  PerformanceScore  Salary  Cost_Index
0  Production         Michael Albert               NaN   62506    63131.06
1              IT/IS      Simon Roup               NaN  104437   122191.29
2  Production         Kissy Sullivan               NaN   64955    66903.65
3  Production           Elijiah Gray               NaN   64991    74739.65
4  Production         Webster Butler               NaN   50825    51841.50

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=5de8e3f5-0f25-4dba-a6d9-d0eb48da4eda' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>